"""empty message

Revision ID: 9adec85b7024
Revises: 
Create Date: 2022-07-26 23:05:56.651773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9adec85b7024"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "example",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("example")
    # ### end Alembic commands ###
